// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package cpctl

type DummyResult struct {
	MutationID string `json:"mutationId"`
}

type NetnsFilter struct {
	Name *string `json:"name"`
}

type NetnsResult struct {
	Name string `json:"name"`
	Pid  int    `json:"pid"`
}
