// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package localui

type AvailableNodesResult struct {
	Node []string `json:"node"`
}

type SelectNodeResult struct {
	MutationID string `json:"mutationID"`
}
