// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package localui

type AuthenticateResult struct {
	MutationID string `json:"mutationId"`
}

type SSHKeyInput struct {
	AuthorizedKey string `json:"authorizedKey"`
}

type SSHKeyResult struct {
	AuthorizedKeys []string `json:"authorizedKeys"`
}
