---
name: ci_checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  lint:
    name: ci_checks
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Check formatting
        run: gofmt -l .

      - name: Check that generated code is up to date
        run: |
          go generate ./...
          git diff --exit-code

  test:
    name: test
    strategy:
      matrix:
        go-version:
          - 1.18
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go build dirs
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Run tests
        run: go test ./... -count=1 -race

