name: dependabot-auto-merge

on:
  pull_request_target:

jobs:
  dependabot-auto-merge:
    if: sender.login == 'dependabot[bot]' || sender.login == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: major
          github-token: ${{ secrets.ACTIONS_GHJM_PAT }}
